name: Publish to package managers

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  winget:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest

    steps:
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          target: x86_64-unknown-linux-gnu

      - name: Update Packages
        uses: michidk/winget-updater@v1
        with:
          komac-token: ${{ secrets.WINGET_TOKEN }} # this has to be a `workflow` classic gh token
          identifier: Mylloon.dsr
          repo: ${{ forgejo.repository }}
          url: "${{ forgejo.server_url }}/${{ forgejo.repository }}/releases/download/{VERSION}/dsr-win32-x64-{VERSION}.zip"
          custom-fork-owner: Mylloon

  aur:
    runs-on: docker
    container:
      image: node

    steps:
      - name: Update AUR package
        uses: varabyte/update-aur-package@v1.0.4
        with:
          version: ${{ forgejo.ref_name }}
          package_name: dsr
          commit_username: "Forgejo Action"
          commit_email: forgejo@noreply.git.mylloon.fr
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
