name: Upload release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: docker
    container:
      image: node

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt-get update &&
          apt-get install -y zip dotnet-sdk-10.0

      - name: Build the app for Windows
        run: |
          npm install --platform=win32 &&
          npm run make -- --platform=win32

      - name: Build the exe installer for Windows
        run: |
          cd winInstaller && make publish

      - name: Clear the node packages
        run: rm -rf node_modules/

      - name: Build the app for Linux
        run: |
          npm install --platform=linux &&
          npm run make -- --platform=linux

      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          files: |-
            out/make/zip/**/*.zip
            winInstaller/bin/Release/net10.0/win-x64/publish/*.exe
          draft: true
