name: Upload release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install --platform=win32 &&
          apt-get update &&
          apt-get install -y zip

      - name: Build the app
        run: npm run make -- --platform=win32

      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          files: out/make/zip/win32/x64/dsr-win32-x64-${{ github.ref_name }}.zip
